### PR TITLE
Auto detect input language as default

### PR DESCRIPTION
**Pull request by grandeljay**
I suggest the default for source language to be empty (auto-detect)

https://www.deepl.com/docs-api/translating-text/request/

### CODE REVIEW

**Review by VimS — COMMENTED** [review]
As much as it pains me to say it:
This change would impact all the users of the library that work with the default implemented in 2018 that the source-language is "de".
This is the main reason we did not change it with the last great update in 2020.

Any suggestions or wishes are welcome.

**Comment by grandeljay** [comment]
Are you using semantic versioning? Maybe the change can be introduced in a new, "breaking changes" version?

Composer should handle the versioning and keep production sites running by not automatically updating to a new major, breaking version.

**Comment by VimS** [comment]
Yeah we use semantic versioning. But you know how lazy some users tag the Versions in their composer.json.
I'll talk to the Team, but I think we can release it as Version 4. Which will probably be the last release anyway.

**Comment by grandeljay** [comment]
> Which will probably be the last release anyway.

😱 if for whatever reason you are no longer maintaining this project, please consider reaching out. This project has been a blessing for me and I would love to keep it alive.

**Comment by VimS** [comment]
The main reason we will stop maintaining this project is that DeepL is about to release it's own [PHP-Library](https://github.com/DeepLcom/deepl-php/)

**Comment by VimS** [comment]
I just found out that "Hallo Welt" ist detected as italian by DeepL so beware of this change!  :rofl:

**Pull request merged**
