### PR TITLE
PHP8 Support

### PR DESCRIPTION
**Pull request by floranpagliai**
Hello, I made the repo supporting PHP8, it's breaking lower version so I don't how you will like to handle this, tell me and I can make changes.

### CODE REVIEW

**Comment by VimS** [comment]
I am not a fan of a PHP8-only-Version, but right now I can't find the time to look into it.
Backward compatibility is important to us.
Although we are ready to drop support for Versions lower than 7. ;)
If anyone using this Library has an opinion regarding this topic, please share it with us..

**Comment by arkadiusjonczek** [comment]
I would suggest to create a feature branch `php8` so that @floranpagliai can merge his changes into this branch instead of master branch.
Based on composer documentation (https://getcomposer.org/doc/articles/versions.md#branches) it then would be possible to use this branch with dev-php8 in composer e.g. `composer require babymarkt/deepl-php-lib dev-php8`. I don't know if there is something to be done to make this branch visible in composer or if creating the branch in git is enough. But this wouldn't break the current release and it also would be possible to use the php8 version.

**Comment by floranpagliai** [comment]
It's possible to make the repo compatible with php8 without breaking php7, by not using new features.

It's a really good idea @arkadiusjonczek, making a non bc version is harder so if each repo was making a branch to start supporting new version it would make our lives easier.

**Comment by BlackbitDevs** [comment]
Any news on that? I think when we just allow PHP 8 and keep the code as it is currently, there won't be any problems. This could be released and thus it will be compatible with PHP 8. 
Afterwards create a branch named `3.0`. There we could add the PHP 8 language features like property types. Adjustments to the code could then be done in dev-master (= BC version) and merged into `3.0`. Once we decide to drop PHP 7 support, we merge `3.0` to the master branch. This even allows for parallel releases of PHP7-BC tags and PHP8-only tags.

**Comment by Sasti** [comment]
We discussed this today internally. Our plan is as follows.
- We won't merge this pull request because we want to pursue the gradient approach of dropping support when the live time of a PHP-Versions fades out. 
- We will provide a tag on an old Version which can be used to support PHP 5.3 -> PHP 7. We will fix the old build so that the PHPUnit tests work again. After that we won't put any more effort in maintaining the old version. When working pull requests are created we will merge them but don't intend to give support. Further information on this tag will follow by one of my colleagues. 
- We will create a new version 3.0? which is compatible with PHP 7.3 till 8.0. My attempt on this is as follows https://github.com/Baby-Markt/deepl-php-lib/pull/22 This might be the basis for further work. The first plan was to even keep support for PHP 5.3 upwards. I dropped the idea very soon when I realized PHPUnit dropped support quite some versions in the past.

**Pull request closed without merging**
